name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: CGO_ENABLED=1 go build -v -tags "sqlite_foreign_keys fts5" ./...
      - name: Test with the Go CLI
        continue-on-error: true
        env: 
          CGO_ENABLED: 1 
        run: go test -v -tags "sqlite_foreign_keys fts5" -json ./...
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-1.24
          path: testResult.json
